# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod tidy
builds:
  - binary: leetcode-cli
    env:
    - CGO_ENABLED=0
    goarch:
      - amd64
    goos:
      - linux
      - darwin

checksum:
  name_template: 'checksums.txt'

dockers:
  - goos: linux
    goarch: amd64
    binaries:
      - leetcode-cli
    skip_push: false
    dockerfile: Dockerfile
    image_templates:
      - yeya24/leetcode-cli:{{.Version}}
